### ISSUE TITLE
ChArUco Board Tracking

### ISSUE THREAD

**Issue by kevinbein** [Brucknem/Volumetric-Fusion#25]
For the camera calibration we should be using a ChArUco board instead of a single ArUco image. As mentioned in the OpenCV documentation, it is more robust and stable with the price of some performance loss.

https://docs.opencv.org/3.4/df/d4a/tutorial_charuco_detection.html

This is fine for camera calibration since here, precision is the key factor.

**Comment by Brucknem** [comment]
As #26 gave really poor results we are back to the board. 
- The tracking is really good and robust with the board. 
- We have the single huge board which is really clear for even big scenes
- We can use it to calibrate 2 cameras a step and then turn around to calibrate the next two
- By doing so we can calculate the relative poses sequentially

**Comment by Brucknem** [comment]
Is working really nice now. Further calibration work in #23
